USE AdventureWorks2022; -- (Cambia tu Base de datos)
GO

-- 1. Crear la tabla

IF OBJECT_ID('dbo.CountryFlags','U') IS NOT NULL
    DROP TABLE dbo.CountryFlags;
GO

CREATE TABLE dbo.CountryFlags (
    Country    NVARCHAR(100) NOT NULL,
    Continent  NVARCHAR(30)  NOT NULL,
    CountryRegionCode       CHAR(2)       NOT NULL PRIMARY KEY,
    Flag_URL   NVARCHAR(255) NOT NULL
);
GO

-- 2. Insertar los registros --

INSERT INTO dbo.CountryFlags (Country, Continent,      CountryRegionCode      , Flag_URL) VALUES
(N'Argelia',N'Africa','DZ',N'https://flagcdn.com/w320/dz.png'),
(N'Angola',N'Africa','AO',N'https://flagcdn.com/w320/ao.png'),
(N'Benin',N'Africa','BJ',N'https://flagcdn.com/w320/bj.png'),
(N'Botsuana',N'Africa','BW',N'https://flagcdn.com/w320/bw.png'),
(N'Burkina Faso',N'Africa','BF',N'https://flagcdn.com/w320/bf.png'),
(N'Burundi',N'Africa','BI',N'https://flagcdn.com/w320/bi.png'),
(N'Cabo Verde',N'Africa','CV',N'https://flagcdn.com/w320/cv.png'),
(N'Camerun',N'Africa','CM',N'https://flagcdn.com/w320/cm.png'),
(N'Chad',N'Africa','TD',N'https://flagcdn.com/w320/td.png'),
(N'Comoras',N'Africa','KM',N'https://flagcdn.com/w320/km.png'),
(N'Costa de Marfil',N'Africa','CI',N'https://flagcdn.com/w320/ci.png'),
(N'Egipto',N'Africa','EG',N'https://flagcdn.com/w320/eg.png'),
(N'Eritrea',N'Africa','ER',N'https://flagcdn.com/w320/er.png'),
(N'Esuatini',N'Africa','SZ',N'https://flagcdn.com/w320/sz.png'),
(N'Etiopia',N'Africa','ET',N'https://flagcdn.com/w320/et.png'),
(N'Gabon',N'Africa','GA',N'https://flagcdn.com/w320/ga.png'),
(N'Gambia',N'Africa','GM',N'https://flagcdn.com/w320/gm.png'),
(N'Ghana',N'Africa','GH',N'https://flagcdn.com/w320/gh.png'),
(N'Guinea',N'Africa','GN',N'https://flagcdn.com/w320/gn.png'),
(N'Guinea-Bisau',N'Africa','GW',N'https://flagcdn.com/w320/gw.png'),
(N'Guinea Ecuatorial',N'Africa','GQ',N'https://flagcdn.com/w320/gq.png'),
(N'Kenia',N'Africa','KE',N'https://flagcdn.com/w320/ke.png'),
(N'Lesoto',N'Africa','LS',N'https://flagcdn.com/w320/ls.png'),
(N'Liberia',N'Africa','LR',N'https://flagcdn.com/w320/lr.png'),
(N'Libia',N'Africa','LY',N'https://flagcdn.com/w320/ly.png'),
(N'Madagascar',N'Africa','MG',N'https://flagcdn.com/w320/mg.png'),
(N'Malaui',N'Africa','MW',N'https://flagcdn.com/w320/mw.png'),
(N'Mali',N'Africa','ML',N'https://flagcdn.com/w320/ml.png'),
(N'Marruecos',N'Africa','MA',N'https://flagcdn.com/w320/ma.png'),
(N'Mauritania',N'Africa','MR',N'https://flagcdn.com/w320/mr.png'),
(N'Mauricio',N'Africa','MU',N'https://flagcdn.com/w320/mu.png'),
(N'Mozambique',N'Africa','MZ',N'https://flagcdn.com/w320/mz.png'),
(N'Namibia',N'Africa','NA',N'https://flagcdn.com/w320/na.png'),
(N'Niger',N'Africa','NE',N'https://flagcdn.com/w320/ne.png'),
(N'Nigeria',N'Africa','NG',N'https://flagcdn.com/w320/ng.png'),
(N'Republica Centroafricana',N'Africa','CF',N'https://flagcdn.com/w320/cf.png'),
(N'Republica del Congo',N'Africa','CG',N'https://flagcdn.com/w320/cg.png'),
(N'Republica Democratica del Congo',N'Africa','CD',N'https://flagcdn.com/w320/cd.png'),
(N'Ruanda',N'Africa','RW',N'https://flagcdn.com/w320/rw.png'),
(N'Santo Tome y Principe',N'Africa','ST',N'https://flagcdn.com/w320/st.png'),
(N'Senegal',N'Africa','SN',N'https://flagcdn.com/w320/sn.png'),
(N'Seychelles',N'Africa','SC',N'https://flagcdn.com/w320/sc.png'),
(N'Sierra Leona',N'Africa','SL',N'https://flagcdn.com/w320/sl.png'),
(N'Somalia',N'Africa','SO',N'https://flagcdn.com/w320/so.png'),
(N'Sudafrica',N'Africa','ZA',N'https://flagcdn.com/w320/za.png'),
(N'Sudan',N'Africa','SD',N'https://flagcdn.com/w320/sd.png'),
(N'Sudan del Sur',N'Africa','SS',N'https://flagcdn.com/w320/ss.png'),
(N'Tanzania',N'Africa','TZ',N'https://flagcdn.com/w320/tz.png'),
(N'Togo',N'Africa','TG',N'https://flagcdn.com/w320/tg.png'),
(N'Tunez',N'Africa','TN',N'https://flagcdn.com/w320/tn.png'),
(N'Uganda',N'Africa','UG',N'https://flagcdn.com/w320/ug.png'),
(N'Yibuti',N'Africa','DJ',N'https://flagcdn.com/w320/dj.png'),
(N'Zambia',N'Africa','ZM',N'https://flagcdn.com/w320/zm.png'),
(N'Zimbabue',N'Africa','ZW',N'https://flagcdn.com/w320/zw.png'),
(N'Afganistan',N'Asia','AF',N'https://flagcdn.com/w320/af.png'),
(N'Arabia Saudita',N'Asia','SA',N'https://flagcdn.com/w320/sa.png'),
(N'Armenia',N'Asia','AM',N'https://flagcdn.com/w320/am.png'),
(N'Azerbaiyan',N'Asia','AZ',N'https://flagcdn.com/w320/az.png'),
(N'Barein',N'Asia','BH',N'https://flagcdn.com/w320/bh.png'),
(N'Banglades',N'Asia','BD',N'https://flagcdn.com/w320/bd.png'),
(N'Butan',N'Asia','BT',N'https://flagcdn.com/w320/bt.png'),
(N'Brunei',N'Asia','BN',N'https://flagcdn.com/w320/bn.png'),
(N'Camboya',N'Asia','KH',N'https://flagcdn.com/w320/kh.png'),
(N'Catar',N'Asia','QA',N'https://flagcdn.com/w320/qa.png'),
(N'China',N'Asia','CN',N'https://flagcdn.com/w320/cn.png'),
(N'Corea del Norte',N'Asia','KP',N'https://flagcdn.com/w320/kp.png'),
(N'Corea del Sur',N'Asia','KR',N'https://flagcdn.com/w320/kr.png'),
(N'Emiratos Arabes Unidos',N'Asia','AE',N'https://flagcdn.com/w320/ae.png'),
(N'Filipinas',N'Asia','PH',N'https://flagcdn.com/w320/ph.png'),
(N'Georgia',N'Asia','GE',N'https://flagcdn.com/w320/ge.png'),
(N'India',N'Asia','IN',N'https://flagcdn.com/w320/in.png'),
(N'Indonesia',N'Asia','ID',N'https://flagcdn.com/w320/id.png'),
(N'Irak',N'Asia','IQ',N'https://flagcdn.com/w320/iq.png'),
(N'Iran',N'Asia','IR',N'https://flagcdn.com/w320/ir.png'),
(N'Israel',N'Asia','IL',N'https://flagcdn.com/w320/il.png'),
(N'Japon',N'Asia','JP',N'https://flagcdn.com/w320/jp.png'),
(N'Jordania',N'Asia','JO',N'https://flagcdn.com/w320/jo.png'),
(N'Kazajistan',N'Asia','KZ',N'https://flagcdn.com/w320/kz.png'),
(N'Kirguistan',N'Asia','KG',N'https://flagcdn.com/w320/kg.png'),
(N'Kuwait',N'Asia','KW',N'https://flagcdn.com/w320/kw.png'),
(N'Laos',N'Asia','LA',N'https://flagcdn.com/w320/la.png'),
(N'Libano',N'Asia','LB',N'https://flagcdn.com/w320/lb.png'),
(N'Malasia',N'Asia','MY',N'https://flagcdn.com/w320/my.png'),
(N'Maldivas',N'Asia','MV',N'https://flagcdn.com/w320/mv.png'),
(N'Mongolia',N'Asia','MN',N'https://flagcdn.com/w320/mn.png'),
(N'Myanmar',N'Asia','MM',N'https://flagcdn.com/w320/mm.png'),
(N'Nepal',N'Asia','NP',N'https://flagcdn.com/w320/np.png'),
(N'Oman',N'Asia','OM',N'https://flagcdn.com/w320/om.png'),
(N'Pakistan',N'Asia','PK',N'https://flagcdn.com/w320/pk.png'),
(N'Palestina',N'Asia','PS',N'https://flagcdn.com/w320/ps.png'),
(N'Singapur',N'Asia','SG',N'https://flagcdn.com/w320/sg.png'),
(N'Siria',N'Asia','SY',N'https://flagcdn.com/w320/sy.png'),
(N'Sri Lanka',N'Asia','LK',N'https://flagcdn.com/w320/lk.png'),
(N'Tayikistan',N'Asia','TJ',N'https://flagcdn.com/w320/tj.png'),
(N'Tailandia',N'Asia','TH',N'https://flagcdn.com/w320/th.png'),
(N'Timor Oriental',N'Asia','TL',N'https://flagcdn.com/w320/tl.png'),
(N'Turkmenistan',N'Asia','TM',N'https://flagcdn.com/w320/tm.png'),
(N'Turquia',N'Asia','TR',N'https://flagcdn.com/w320/tr.png'),
(N'Uzbekistan',N'Asia','UZ',N'https://flagcdn.com/w320/uz.png'),
(N'Vietnam',N'Asia','VN',N'https://flagcdn.com/w320/vn.png'),
(N'Yemen',N'Asia','YE',N'https://flagcdn.com/w320/ye.png'),
(N'Taiwan',N'Asia','TW',N'https://flagcdn.com/w320/tw.png'),
(N'Albania',N'Europa','AL',N'https://flagcdn.com/w320/al.png'),
(N'Alemania',N'Europa','DE',N'https://flagcdn.com/w320/de.png'),
(N'Andorra',N'Europa','AD',N'https://flagcdn.com/w320/ad.png'),
(N'Austria',N'Europa','AT',N'https://flagcdn.com/w320/at.png'),
(N'Belgica',N'Europa','BE',N'https://flagcdn.com/w320/be.png'),
(N'Bielorrusia',N'Europa','BY',N'https://flagcdn.com/w320/by.png'),
(N'Bosnia y Herzegovina',N'Europa','BA',N'https://flagcdn.com/w320/ba.png'),
(N'Bulgaria',N'Europa','BG',N'https://flagcdn.com/w320/bg.png'),
(N'Chequia',N'Europa','CZ',N'https://flagcdn.com/w320/cz.png'),
(N'Chipre',N'Europa','CY',N'https://flagcdn.com/w320/cy.png'),
(N'Croacia',N'Europa','HR',N'https://flagcdn.com/w320/hr.png'),
(N'Dinamarca',N'Europa','DK',N'https://flagcdn.com/w320/dk.png'),
(N'Eslovaquia',N'Europa','SK',N'https://flagcdn.com/w320/sk.png'),
(N'Eslovenia',N'Europa','SI',N'https://flagcdn.com/w320/si.png'),
(N'España',N'Europa','ES',N'https://flagcdn.com/w320/es.png'),
(N'Estonia',N'Europa','EE',N'https://flagcdn.com/w320/ee.png'),
(N'Finlandia',N'Europa','FI',N'https://flagcdn.com/w320/fi.png'),
(N'Francia',N'Europa','FR',N'https://flagcdn.com/w320/fr.png'),
(N'Grecia',N'Europa','GR',N'https://flagcdn.com/w320/gr.png'),
(N'Hungria',N'Europa','HU',N'https://flagcdn.com/w320/hu.png'),
(N'Irlanda',N'Europa','IE',N'https://flagcdn.com/w320/ie.png'),
(N'Islandia',N'Europa','IS',N'https://flagcdn.com/w320/is.png'),
(N'Italia',N'Europa','IT',N'https://flagcdn.com/w320/it.png'),
(N'Letonia',N'Europa','LV',N'https://flagcdn.com/w320/lv.png'),
(N'Liechtenstein',N'Europa','LI',N'https://flagcdn.com/w320/li.png'),
(N'Lituania',N'Europa','LT',N'https://flagcdn.com/w320/lt.png'),
(N'Luxemburgo',N'Europa','LU',N'https://flagcdn.com/w320/lu.png'),
(N'Malta',N'Europa','MT',N'https://flagcdn.com/w320/mt.png'),
(N'Moldavia',N'Europa','MD',N'https://flagcdn.com/w320/md.png'),
(N'Monaco',N'Europa','MC',N'https://flagcdn.com/w320/mc.png'),
(N'Montenegro',N'Europa','ME',N'https://flagcdn.com/w320/me.png'),
(N'Macedonia del Norte',N'Europa','MK',N'https://flagcdn.com/w320/mk.png'),
(N'Noruega',N'Europa','NO',N'https://flagcdn.com/w320/no.png'),
(N'Paises Bajos',N'Europa','NL',N'https://flagcdn.com/w320/nl.png'),
(N'Polonia',N'Europa','PL',N'https://flagcdn.com/w320/pl.png'),
(N'Portugal',N'Europa','PT',N'https://flagcdn.com/w320/pt.png'),
(N'Reino Unido',N'Europa','GB',N'https://flagcdn.com/w320/gb.png'),
(N'Rumania',N'Europa','RO',N'https://flagcdn.com/w320/ro.png'),
(N'Rusia',N'Europa','RU',N'https://flagcdn.com/w320/ru.png'),
(N'San Marino',N'Europa','SM',N'https://flagcdn.com/w320/sm.png'),
(N'Serbia',N'Europa','RS',N'https://flagcdn.com/w320/rs.png'),
(N'Suecia',N'Europa','SE',N'https://flagcdn.com/w320/se.png'),
(N'Suiza',N'Europa','CH',N'https://flagcdn.com/w320/ch.png'),
(N'Ucrania',N'Europa','UA',N'https://flagcdn.com/w320/ua.png'),
(N'Ciudad del Vaticano',N'Europa','VA',N'https://flagcdn.com/w320/va.png'),
(N'Kosovo',N'Europa','XK',N'https://flagcdn.com/w320/xk.png'),
(N'Antigua y Barbuda',N'Norteamerica','AG',N'https://flagcdn.com/w320/ag.png'),
(N'Bahamas',N'Norteamerica','BS',N'https://flagcdn.com/w320/bs.png'),
(N'Barbados',N'Norteamerica','BB',N'https://flagcdn.com/w320/bb.png'),
(N'Belice',N'Norteamerica','BZ',N'https://flagcdn.com/w320/bz.png'),
(N'Canada',N'Norteamerica','CA',N'https://flagcdn.com/w320/ca.png'),
(N'Costa Rica',N'Norteamerica','CR',N'https://flagcdn.com/w320/cr.png'),
(N'Cuba',N'Norteamerica','CU',N'https://flagcdn.com/w320/cu.png'),
(N'Dominica',N'Norteamerica','DM',N'https://flagcdn.com/w320/dm.png'),
(N'Republica Dominicana',N'Norteamerica','DO',N'https://flagcdn.com/w320/do.png'),
(N'El Salvador',N'Norteamerica','SV',N'https://flagcdn.com/w320/sv.png'),
(N'Estados Unidos',N'Norteamerica','US',N'https://flagcdn.com/w320/us.png'),
(N'Granada',N'Norteamerica','GD',N'https://flagcdn.com/w320/gd.png'),
(N'Guatemala',N'Norteamerica','GT',N'https://flagcdn.com/w320/gt.png'),
(N'Haiti',N'Norteamerica','HT',N'https://flagcdn.com/w320/ht.png'),
(N'Honduras',N'Norteamerica','HN',N'https://flagcdn.com/w320/hn.png'),
(N'Jamaica',N'Norteamerica','JM',N'https://flagcdn.com/w320/jm.png'),
(N'Mexico',N'Norteamerica','MX',N'https://flagcdn.com/w320/mx.png'),
(N'Nicaragua',N'Norteamerica','NI',N'https://flagcdn.com/w320/ni.png'),
(N'Panama',N'Norteamerica','PA',N'https://flagcdn.com/w320/pa.png'),
(N'San Cristobal y Nieves',N'Norteamerica','KN',N'https://flagcdn.com/w320/kn.png'),
(N'San Vicente y las Granadinas',N'Norteamerica','VC',N'https://flagcdn.com/w320/vc.png'),
(N'Santa Lucia',N'Norteamerica','LC',N'https://flagcdn.com/w320/lc.png'),
(N'Trinidad y Tobago',N'Norteamerica','TT',N'https://flagcdn.com/w320/tt.png'),
(N'Argentina',N'Sudamerica','AR',N'https://flagcdn.com/w320/ar.png'),
(N'Bolivia',N'Sudamerica','BO',N'https://flagcdn.com/w320/bo.png'),
(N'Brasil',N'Sudamerica','BR',N'https://flagcdn.com/w320/br.png'),
(N'Chile',N'Sudamerica','CL',N'https://flagcdn.com/w320/cl.png'),
(N'Colombia',N'Sudamerica','CO',N'https://flagcdn.com/w320/co.png'),
(N'Ecuador',N'Sudamerica','EC',N'https://flagcdn.com/w320/ec.png'),
(N'Guyana',N'Sudamerica','GY',N'https://flagcdn.com/w320/gy.png'),
(N'Paraguay',N'Sudamerica','PY',N'https://flagcdn.com/w320/py.png'),
(N'Peru',N'Sudamerica','PE',N'https://flagcdn.com/w320/pe.png'),
(N'Surinam',N'Sudamerica','SR',N'https://flagcdn.com/w320/sr.png'),
(N'Uruguay',N'Sudamerica','UY',N'https://flagcdn.com/w320/uy.png'),
(N'Venezuela',N'Sudamerica','VE',N'https://flagcdn.com/w320/ve.png'),
(N'Australia',N'Oceania','AU',N'https://flagcdn.com/w320/au.png'),
(N'Estados Federados de Micronesia',N'Oceania','FM',N'https://flagcdn.com/w320/fm.png'),
(N'Fiyi',N'Oceania','FJ',N'https://flagcdn.com/w320/fj.png'),
(N'Kiribati',N'Oceania','KI',N'https://flagcdn.com/w320/ki.png'),
(N'Islas Marshall',N'Oceania','MH',N'https://flagcdn.com/w320/mh.png'),
(N'Nauru',N'Oceania','NR',N'https://flagcdn.com/w320/nr.png'),
(N'Nueva Zelanda',N'Oceania','NZ',N'https://flagcdn.com/w320/nz.png'),
(N'Palaos',N'Oceania','PW',N'https://flagcdn.com/w320/pw.png'),
(N'Papua Nueva Guinea',N'Oceania','PG',N'https://flagcdn.com/w320/pg.png'),
(N'Samoa',N'Oceania','WS',N'https://flagcdn.com/w320/ws.png'),
(N'Islas Salomon',N'Oceania','SB',N'https://flagcdn.com/w320/sb.png'),
(N'Tonga',N'Oceania','TO',N'https://flagcdn.com/w320/to.png'),
(N'Tuvalu',N'Oceania','TV',N'https://flagcdn.com/w320/tv.png'),
(N'Vanuatu',N'Oceania','VU',N'https://flagcdn.com/w320/vu.png');
GO

select * from dbo.CountryFlags
